### ISSUE TITLE
New mvnw script breaks release train script

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud-samples/scripts#21]
The new `mvnw` script `echo`s several things, for example
```
Running version check
The found version is [2.0.0.M2]
Activating "milestone" profile for version="2.0.0.M2"
Deactivating "central" profile for version="2.0.0.M2"
```
This breaks the `retrieve_version_from_maven` function in `release_train.sh` because it doesn't expect this extra text being printed when maven is run.

The easiest options to fix this is to remove the `echo` commands in `mvnw`, but the next time we update the file we are probably going to run into the same issue.  The better option would be to update the `retrieve_version_from_maven` function to try an parse out the version number.

@marcingrzejszczak

**Comment by ryanjbaxter** [comment]
I think if we change `retrieve_version_from_maven` to 
```
function retrieve_version_from_maven() {
  RETRIEVED_VERSION=$("${MAVEN_EXEC}" -q \
        -Dexec.executable="echo" \
        -Dexec.args="\${spring-cloud-${1}.version}" \
        org.codehaus.mojo:exec-maven-plugin:1.3.1:exec \
        -o -pl spring-cloud-dependencies | sed '$!d')
    echo "Extracted version for project [$1] from Maven build is [${RETRIEVED_VERSION}]"
}
```
we can fix the problem.  `sed '$!d'` will extract the last line from the text, which contains the version number.

**Comment by marcingrzejszczak** [comment]
We can also do `tail -1` AFAIR - so if you tested that then I'm all for doing that change!

**Comment by ryanjbaxter** [comment]
Awesome thanks @marcingrzejszczak!
