### ISSUE TITLE
Dalston documentation contains reference to old versions of Cloud and Boot

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud-samples/scripts#23]
The documentation for Dalston (I was looking at [SR3](http://cloud.spring.io/spring-cloud-static/Dalston.SR3)) contains several references to Brixton and Camden. It also references Boot 1.3 in a few places. Typically this happens in sample `pom.xml` or `build.gradle` snippets. Here's [one example](http://cloud.spring.io/spring-cloud-static/Dalston.SR3/#_client_side_usage).

**Comment by spencergibb** [comment]
Fixed in individual repos
