### ISSUE TITLE
Add Spring Cloud GCP To Docs

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud-samples/scripts#28]
Work has already been done, but need a new GCP release to test it
https://github.com/spring-cloud-samples/scripts/commit/e071d8b8253e04d38585014570adae1c7fc0ed8d

cc: @artembilan

**Comment by artembilan** [comment]
Huh? Doesn't sound so efficient to release a new version, test then fix possible bugs an release again.
And so on, so on...

Can't we really emulate a release train against BUILD-SNAPSHOTs?
Actually what we need here is just Docs...

Sorry if I sounds silly.

Thanks for the heads up anyway!

**Comment by ryanjbaxter** [comment]
Unfortunately we cant test with BUILD-SNAPSHOT I dont think because there is not tag in GitHub.

Maybe @marcingrzejszczak knows a way.

**Comment by artembilan** [comment]
My concern that we might need to change something in `adoc` files to make it consistent with other Spring Cloud project.
That's why would be great to see the whole picture before we really go for releasing.

**Comment by ryanjbaxter** [comment]
I agree, lets see what @marcingrzejszczak says after he gets back from vacation

**Comment by marcingrzejszczak** [comment]
already added
